
"""Program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiuO07t5WIT9YJAVadsE9fb9YvDjG8p1
"""
import mysql.connector
  
db = mysql.connector.connect(
  host="localhost",
  user="root", 
  passwd="imaanabrarcassim2005",
  database="college"
)

mycursor = db.cursor()
mycursor.execute("SELECT * FROM students")

for x in mycursor:
    print(x)
