
"""Program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiuO07t5WIT9YJAVadsE9fb9YvDjG8p1
"""
import mysql.connector
  
db = mysql.connector.connect(
  host="localhost",
  user="root", 
  passwd="imaanabrarcassim2005",
  database="college"
)

mycursor = db.cursor()
mycursor.execute("SELECT * FROM grades")

for x in mycursor:
    print(x)


#df = pd.read_database('college')

#df['Average']=df.mean(axis=1).round(1)

#df['Grade'] = pd.cut(df['Average'], bins=[0 , 39 , 49, 59, 69, 70 ,100 ], labels= ['F','E', 'D', 'C', 'B', 'A'])
#df.iloc[0:11,[0,1,6,7]]
